name: HUB
author: Blockcade
version: 1.0
api-version: 1.13
main: net.blockcade.HUB.Main
commands:
  debug:
    description: Testing command, remove
  fly:
    description: Toggle flight for players.
  spawn:
    description: Teleport to the spawn
    aliases:
      - home
      - respawn